// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs0ZqWXueXwCBzeK8etxTcG7xjwmdm4c4',
    appId: '1:550239393196:web:09adec41de051e2a931609',
    messagingSenderId: '550239393196',
    projectId: 'bankingapp-6afda',
    authDomain: 'bankingapp-6afda.firebaseapp.com',
    storageBucket: 'bankingapp-6afda.appspot.com',
    measurementId: 'G-C9DQG73PK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFHfEKbacsYz_Ogg9LBpB-chiT7FXeo4',
    appId: '1:550239393196:android:26de1b0547145e2c931609',
    messagingSenderId: '550239393196',
    projectId: 'bankingapp-6afda',
    storageBucket: 'bankingapp-6afda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ar-ifAVf-PjWlTDpyBSzxhA2At1uOZ4',
    appId: '1:550239393196:ios:85ea665823db1ef7931609',
    messagingSenderId: '550239393196',
    projectId: 'bankingapp-6afda',
    storageBucket: 'bankingapp-6afda.appspot.com',
    iosBundleId: 'com.example.bankapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ar-ifAVf-PjWlTDpyBSzxhA2At1uOZ4',
    appId: '1:550239393196:ios:c4e9fe212247334d931609',
    messagingSenderId: '550239393196',
    projectId: 'bankingapp-6afda',
    storageBucket: 'bankingapp-6afda.appspot.com',
    iosBundleId: 'com.example.bankapp.RunnerTests',
  );
}
